name: S3 Build
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            
            - name: Login Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Setup Docker Buildx
                uses: docker/setup-buildx-action@v2
                id: buildx

            - name: Build and Push Docker Image
                uses: docker/build-push-action@v4
                with:
                    context: ./
                    file: ./Dockerfile
                    push: true
                    tags: baonx/bt6:latest

            - name: Build, run to server
                id: build-run
                run: |
                    mkdir -p ~/.ssh
                    ssh-keyscan -H $SSH_ADDRESS  >> ~/.ssh/known_hosts
                    echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa
                    ssh ubuntu@$SSH_ADDRESS "cd /var/www/html; docker pull baonx/bt6:latest; docker run --name bt6 -it -p 3000:3000 baonx/bt6:latest"
